server:
  port: 8080

spring:
  datasource:
    username: root
    password: qq85591662.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.94.244/myframe?serverTimeZone=Asia/ShangHai&useUnicode=true&characterEncoding=UTF8&useSSL=false
    druid:
      min-idle: 20
      max-active: 100
      initial-size: 20
      max-wait: 60000
      #图形化界面配置 url-pattrn:路径
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: qq85591662.
      #配置SQL过滤，打印在图形化界面 log-slow-sql:慢查询配置 slow-sql-millis:慢查询时间。
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true

sql:
  beauty:
    show:
      enabled: true
